### ISSUE TITLE
bspatch、bsdiff : cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by fldroid** [eleme/bspatch#3]
bspatch、bsdiff 是那个系统上的命令，我在Linux报的这个错。

**Comment by JackCho** [comment]
mac，我找找其他两个平台的也给放上来

**Comment by letyouthgoon** [comment]
mac的 bsdiff不起作用 
![396b857d-7833-4e4b-92ac-449af1ae5b0a](https://cloud.githubusercontent.com/assets/3445575/18613805/82e86948-7db4-11e6-9852-9b54a5d254a0.png)

**Comment by JackCho** [comment]
可以使用的，你看下提示的usage

**Comment by JackCho** [comment]
bsdiff/bspatch works on  all unix platform, and there is also [Windows version](http://www.pokorra.de/coding/bsdiff.html). 
if the cli doesn't work, please google to find something works for you

**Comment by 2dxgujun** [comment]
mac仅自带bspatch命令，bsdiff需要用tools里面的那个bsdiff @letyouthgoon
