### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by wznshuai** [eleme/bspatch#6]
11-30 17:58:38.593 3022-3127/? I/bspatch.c: 开始打包之。。。。。。
11-30 17:58:38.593 3022-3127/? I/bspatch.c: bspatch
11-30 17:58:38.593 3022-3127/? I/bspatch.c: /data/app/com.xxx.xxx.xxx-1/base.apk
11-30 17:58:38.593 3022-3127/? I/bspatch.c: /storage/emulated/0/XXx/xxx/temp/xxx_patch.xxapk
11-30 17:58:38.593 3022-3127/? I/bspatch.c: /storage/emulated/0/xxx/xxx/temp/patch.temp
11-30 17:58:38.593 3022-3127/? I/bspatch.c: Point 0
11-30 17:58:38.593 3022-3127/? I/bspatch.c: Patch is opened
11-30 17:58:38.593 3022-3127/? I/bspatch.c: Point 1
11-30 17:58:38.593 3022-3127/? I/bspatch.c: Point 2
11-30 17:58:38.593 3022-3127/? I/bspatch.c: Point 3
11-30 17:58:38.593 3022-3127/? I/bspatch.c: Point 4
11-30 17:58:38.594 3022-3127/? I/bspatch.c: Point 5
11-30 17:58:38.599 2376-3179/? D/MediaProvider: object removed 213
11-30 17:58:38.600 3022-3127/? I/bspatch.c: Point 6
                                            
                                            [ 11-30 17:58:38.870    80:   80 D/         ]
                                            Socket deconnection
11-30 17:58:39.115 859-983/? I/WindowState: WIN DEATH: Window{21956679 u0 com.xxx.xxx.xxx/com.xxx.xxx.xxx.activity.main.MainActivity}
11-30 17:58:39.118 859-914/? D/WifiService: Client connection lost with reason: 4
11-30 17:58:39.126 577-577/? I/Zygote: Process 3022 exited cleanly (1)
11-30 17:58:39.127 859-1220/? I/ActivityManager: Process com.xx.xxx.xxx (pid 3022) has died

每次用Genymotion 的5.0模拟器都会crash  ，试了一个4.1的模拟器 和  6.0的 三星手机没出现问题

@JackCho

**Comment by JackCho** [comment]
日志信息不够完整，从上看不出什么东西。麻烦把所有的日志都贴上来

**Comment by wznshuai** [comment]
[ 11-30 22:01:20.598    80:   80 D/         ]
                                                                                        Socket deconnection
11-30 22:01:21.610 2376-16879/android.process.media D/DownloadManager: [10] Finished with status SUCCESS
11-30 22:01:21.641 2376-16890/android.process.media W/DownloadManager: Missing request for path /storage/emulated/0/xxx/xxx/temp/patch.temp
                                                                       
                                                                       [ 11-30 22:01:22.599    80:   80 D/         ]
                                                                       Socket deconnection
11-30 22:01:22.622 16736-16845/com.xxx.xxx.xxx I/bspatch.c: 开始打包之。。。。。。
11-30 22:01:22.622 16736-16845/com.xxx.xxx.xxx I/bspatch.c: bspatch
11-30 22:01:22.622 16736-16845/com.xxx.xxx.xxx I/bspatch.c: /data/app/cxxx.xxx.xxx-1/base.apk
11-30 22:01:22.622 16736-16845/com.xxx.xxx.xxx I/bspatch.c: /storage/emulated/0/xxx/xxx/temp/xxx_patch.apk
11-30 22:01:22.622 16736-16845/com.xxx.xxx.xxx I/bspatch.c: /storage/emulated/0/xxxx/xxxx/temp/patch.temp
11-30 22:01:22.622 16736-16845/com.xxx.xxx.xxx I/bspatch.c: Point 0
11-30 22:01:22.623 16736-16845/com.xxx.xxx.xxx I/bspatch.c: Patch is opened
11-30 22:01:22.623 16736-16845/com.xxx.xxx.xxx I/bspatch.c: Point 1
11-30 22:01:22.623 16736-16845/com.xxx.xxx.xxx I/bspatch.c: Point 2
11-30 22:01:22.623 16736-16845/com.xxx.xxx.xxx I/bspatch.c: Point 3
11-30 22:01:22.623 16736-16845/com.xxx.xxx.xxx I/bspatch.c: Point 4
11-30 22:01:22.623 16736-16845/com.xxx.xxx.xxx I/bspatch.c: Point 5
11-30 22:01:22.629 16736-16845/com.xxx.xxx.xxx I/bspatch.c: Point 6
11-30 22:01:22.630 2376-16891/android.process.media D/MediaProvider: object removed 218
11-30 22:01:23.129 859-983/system_process I/WindowState: WIN DEATH: Window{25753d4e u0 com.xxx.xxx.xxx/xxxx.xxx.xxx.xxx.activity.main.MainActivity}
11-30 22:01:23.130 859-914/system_process D/WifiService: Client connection lost with reason: 4
11-30 22:01:23.135 577-577/? I/Zygote: Process 16736 exited cleanly (1)
11-30 22:01:23.138 859-2344/system_process I/ActivityManager: Process com.xxx.xxx.xxx (pid 16736) has died
11-30 22:01:23.139 859-2344/system_process W/ActivityManager: Scheduling restart of crashed service com.xxx.xxx.xxx/com.igexin.sdk.PushServiceUser in 1000ms
11-30 22:01:23.139 859-2344/system_process W/ActivityManager: Force removing ActivityRecord{16130969 u0 com.xxx.xxx.xxx/.activity.main.MainActivity t513}: app died, no saved state
11-30 22:01:23.166 16892-16892/? I/art: Late-enabling -Xcheck:jni
11-30 22:01:23.181 859-876/system_process I/ActivityManager: Start proc com.xxx.xxx.xxx for service com.xxx.xxx.xxx/com.igexin.sdk.PushServiceUser: pid=16892 uid=10079 gids={50079, 9997, 3003, 1028, 1015, 3002, 3001} abi=x86
11-30 22:01:23.195 1192-1414/com.android.launcher3 W/EGL_emulation: eglSurfaceAttrib not implemented
11-30 22:01:23.195 1192-1414/com.android.launcher3 W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xe10b3a40, error=EGL_SUCCESS
11-30 22:01:23.214 859-2344/system_process W/InputMethodManagerService: Got RemoteException sending setActive(false) notification to pid 16736 uid 10079
11-30 22:01:23.259 16892-16892/com.xxx.xxx.xxx D/ProviderStub: onCreate
11-30 22:01:23.283 16892-16892/com.xxx.xxx.xxx E/Amigo: working checksum: 
11-30 22:01:23.284 16892-16892/com.xxx.xxx.xxx D/Amigo: Patch apk doesn't exists
11-30 22:01:23.284 16892-16892/com.xxx.xxx.xxx E/amigo_patch_cleaner: clear
11-30 22:01:23.326 16892-16892/com.xxx.xxx.xxx I/MultiDex: VM with version 2.1.0 has multidex support
11-30 22:01:23.326 16892-16892/com.xxx.xxx.xxx I/MultiDex: install
11-30 22:01:23.326 16892-16892/com.xxx.xxx.xxx I/MultiDex: VM has multidex support, MultiDex support library is disabled.
11-30 22:01:23.329 16892-16892/com.xxx.xxx.xxx D/PRETTYLOGGER-MyApplication: ╔════════════════════════════════════════════════════════════════════════════════════════
11-30 22:01:23.329 16892-16892/com.xxx.xxx.xxx D/PRETTYLOGGER-MyApplication: ║ Thread: main
11-30 22:01:23.329 16892-16892/com.xxx.xxx.xxx D/PRETTYLOGGER-MyApplication: ╟────────────────────────────────────────────────────────────────────────────────────────
11-30 22:01:23.329 16892-16892/com.xxx.xxx.xxx D/PRETTYLOGGER-MyApplication: ║ Amigo.runOriginalApplication  (Amigo.java:271)
11-30 22:01:23.329 16892-16892/com.xxx.xxx.xxx D/PRETTYLOGGER-MyApplication: ║    MyApplication.onCreate  (MyApplication.java:69)
11-30 22:01:23.329 16892-16892/com.xxx.xxx.xxx D/PRETTYLOGGER-MyApplication: ╟────────────────────────────────────────────────────────────────────────────────────────
11-30 22:01:23.329 16892-16892/com.xxx.xxx.xxx D/PRETTYLOGGER-MyApplication: ║ mApp init
11-30 22:01:23.329 16892-16892/com.xxx.xxx.xxx D/PRETTYLOGGER-MyApplication: ╚════════════════════════════════════════════════════════════════════════════════════════

最下面就是Application被重启了 @JackCho

**Comment by wznshuai** [comment]
补一张图片 
![image](https://cloud.githubusercontent.com/assets/1897647/20783313/0495b876-b7ce-11e6-94ed-0084a5cb4244.png)

**Comment by wznshuai** [comment]
}).doOnUnsubscribe(new Action0() {
                    @Override
                    public void call() {
                        downloadManager.remove(downloadId);
                    }
                });
我在RxJava结束监听的时候调用了 remove 导致了 删除了已下载好的patch, 同时合成在进行中，应该是这里导致的问题

**Comment by JackCho** [comment]
👌收到
