### ISSUE TITLE
系统找不到指定的文件

### ISSUE THREAD

**Issue by daizheng521** [eleme/bspatch#7]
Cannot run program "bsdiff": CreateProcess error=2, 系统找不到指定的文件，出现这样的问题,如何解决呢?bsdiff 本身是什么？批处理脚本？

**Comment by JackCho** [comment]
这个bsdiff的版本是mac版的，我回头把linux和windows的都上传上来

**Comment by JackCho** [comment]
https://github.com/eleme/bspatch/tree/master/tools 这下面放了全平台的可执行文件

**Comment by wznshuai** [comment]
同样的问题
